name: Docker Build and Push Multi-Arch

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'server.js'
      - '**.js'
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/sg303/docker-cors-anywhere/cors-anywhere:latest
          platforms: linux/amd64,linux/arm/v7,linux/arm64

